apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-deployment
  namespace: cpsc-5910-lab8
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authorization
  template:
    metadata:
      labels:
        app: authorization
    spec:
      containers:
        - name: authorization
          image: ducphamle212/authorization:latest
          ports:
            - containerPort: 5001

          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"

          env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_SECRET_ACCESS_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: authorization-service
  namespace: cpsc-5910-lab8
spec:
  selector:
    app: authorization
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30000 # Define the NodePort here
  type: NodePort # Change the type to NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-deployment
  namespace: cpsc-5910-lab8
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - name: employee
          image: ducphamle212/employee:latest
          ports:
            - containerPort: 5000

          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: AUTHORIZATION_SERVICE_URL
              value: "http://authorization-service.cpsc-5910-lab8:5001"
            - name: PORT
              value: "5000"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_SECRET_ACCESS_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: employee-service
  namespace: cpsc-5910-lab8
spec:
  selector:
    app: employee
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001 # Define the NodePort here
  type: NodePort # Change the type to NodePort
